version: '3.8'

services:
  db:
    image: postgres:15
    container_name: test_postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped
